name: Run Klee
on:
  push:

jobs:
  run-klee:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
        with:
          ref: a211dd5a7050b1f9e8a9870b95513060e72ac4a0

      - name: Install Dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install luajit openssl@3
          echo "/usr/local/bin" >> $GITHUB_PATH
          echo "/opt/homebrew/bin" >> $GITHUB_PATH
          echo "/opt/local/bin" >> $GITHUB_PATH

      - name: Install Dependency (Linux) 
        if: runner.os == 'Linux' 
        run: | 
          sudo apt-get update 
          sudo apt-get install -y luajit
          
      - name: Build repository 
        run: make
      
      - name: Install Klee and STP dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake curl file g++-multilib gcc-multilib git libcap-dev libunwind-dev libgoogle-perftools-dev libncurses5-dev libsqlite3-dev libtcmalloc-minimal4 python3-pip unzip graphviz doxygen bison flex libboost-all-dev perl zlib1g-dev minisat
          sudo pip3 install lit wllvm
          sudo apt-get install -y clang-13 llvm-13 llvm-13-dev llvm-13-tools 

      - name: Setup MacPorts
        if: runner.os == 'macOS'
        uses: melusina-org/setup-macports@v1.1.4
        
      - name: Install Klee dependencies + STP (macOS)
        if: runner.os == 'macOS'
        run: | 
           brew install curl git cmake python@3.11 unzip gperftools sqlite3 graphviz doxygen bash llvm python-tabulate stp
           sudo pip3 install lit wllvm
           sudo port -v selfupdate
           sudo port install clang-13
           sudo port install llvm-13
           ulimit -s 65532
           echo 'export PATH="/opt/homebrew/opt/llvm@13/bin:/usr/local/opt/llvm@13/bin:$PATH"' >> $GITHUB_ENV
           echo 'export LDFLAGS="-L/opt/homebrew/opt/llvm@13/lib -L/usr/local/opt/llvm@13/lib"' >> $GITHUB_ENV
           echo 'export CPPFLAGS="-I/opt/homebrew/opt/llvm@13/include -I/usr/local/opt/llvm@13/include"' >> $GITHUB_ENV
          
      - name: Install STP (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install cmake bison flex libboost-all-dev perl zlib1g-dev minisat
          git clone https://github.com/stp/stp.git /tmp/stp
          cd /tmp/stp && git checkout tags/2.3.3
          mkdir build && cd build
          cmake .. && make 
          sudo make install
          ulimit -s unlimited
            
      - name: Downloading Google Test Sources (a dependency to Klee)
        run: |
          mkdir -p /tmp/gtest && cd /tmp/gtest
          curl -OL https://github.com/google/googletest/archive/release-1.11.0.zip && unzip release-1.11.0.zip
      
      - name: Build uClibc and the POSIX environment model (Linux only)
        if: runner.os == 'Linux'
        run: |
          git clone https://github.com/klee/klee-uclibc.git /tmp/klee-uclibc
          cd /tmp/klee-uclibc && ./configure --make-llvm-lib --with-cc clang-13 --with-llvm-config llvm-config-13
          make -j2 
          cd ..
      
      - name: Cloning and building libc++ (a dependency to Klee)
        run: | 
          git clone https://github.com/klee/klee.git /tmp/klee
          sudo LLVM_VERSION=13 BASE=/usr/lib ENABLE_OPTIMIZED=1 DISABLE_ASSERTIONS=1 ENABLE_DEBUG=0 REQUIRES_RTTI=1 /tmp/klee/scripts/build/build.sh libcxx
      
      - name: Configuring and Building Klee
        run: |
          cd /tmp/klee
          mkdir build && cd build 
          cmake -DENABLE_SOLVER_STP=ON -DENABLE_POSIX_RUNTIME=ON -DKLEE_UCLIBC_PATH=/tmp/klee-uclibc -DENABLE_UNIT_TESTS=ON -DGTEST_SRC_DIR=/tmp/gtest/googletest-release-1.11.0 ..
          make
      
      - name: Run Klee Analyzer
        run: |
          #!/bin/bash

          set +e 
          
          include_dirs=$(find . -name '*.h' -exec dirname {} + | sort -u | sed 's/^/-I /')
          
          while IFS= read -r -d '' file; do
              bc_file="${file%.c}.bc"
              if clang -I "$include_dirs" -emit-llvm -c -g -O0 -Xclang -disable-O0-optnone "$file" -o "$bc_file" 2>/dev/null; then
                  if ! /usr/lib/llvm-13/bin/llvm-nm "$PWD/$bc_file" | grep -q " T main"; then
                      rm "$bc_file"
                  else
                      klee_output=$(/tmp/klee/build/bin/klee "$bc_file" 2>&1)
                      klee_exit_code=$?
          
                      if [[ $klee_exit_code -eq 0 ]]; then
                          /tmp/klee/build/bin/klee "$bc_file"
                          echo ""
                          echo ""
                          echo ""
                      elif [[ $klee_exit_code -eq 1 && $klee_output =~ "Invalid record" ]]; then
                         	continue 
                      else
                          continue
                      fi
                  fi
              else
                  continue
              fi
          done < <(find . -name "*.c" -exec grep -q "int main" {} \; -print0)
